apiVersion: v1
kind: Pod
metadata:
    name: emby
    labels:
      app: emby
spec:
    containers:
    - name: emby
      image: emby/embyserver:latest
      env:
      - name: UID
        value: "0"
      - name: GID
        value: "0"
      readinessProbe:
        tcpSocket:
          port: 8096
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 8096
        initialDelaySeconds: 15
        periodSeconds: 20
      ports:
        - containerPort: 8096
          protocol: TCP
        - containerPort: 8920
          protocol: TCP
      volumeMounts:
        - mountPath: "/mnt/share1"
          name: share1
        - mountPath: "/config"
          name: config
    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: nfs-mercury-media-emby-claim
      - name: share1
        persistentVolumeClaim:
          claimName: nfs-mercury-config-emby-claim
    restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mercury-media-emby
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - hard
    - vers=3
    - rsize=131072
    - wsize=131072
    - namlen=255
    - timeo=600
    - retrans=2
    - local_lock=none
  nfs:
    server: 192.168.1.149
    path: "/volume1/media"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mercury-config-emby
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - hard
    - vers=3
    - rsize=131072
    - wsize=131072
    - namlen=255
    - timeo=600
    - retrans=2
    - local_lock=none
  nfs:
    server: 192.168.1.149
    path: "/volume1/docker-volumes/emby/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mercury-media-emby-claim
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mercury-config-emby-claim
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: Service
metadata: 
  name: emby-service
spec:
  selector:
    app: emby
  type: NodePort
  ports:
  - name: emby
    port: 8096
    targetPort: 8096
    nodePort: 32401
    protocol: TCP

