apiVersion: v1
kind: Pod
metadata:
    name: plex
    labels:
      app: plex
spec:
    containers:
    - name: plex
      image: plexinc/pms-docker
      env:
        - name: TZ
          value: "America/New York"
        - name: ALLOWED_NETWORKS
          value: "192.168.0.0/22"
      readinessProbe:
        tcpSocket:
          port: 32400
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 32400
        initialDelaySeconds: 15
        periodSeconds: 20
      ports:
        - containerPort: 32400
          protocol: TCP
        - containerPort: 3005
          protocol: TCP
        - containerPort: 8324
          protocol: TCP
        - containerPort: 32469
          protocol: TCP
        - containerPort: 1900
          protocol: UDP
        - containerPort: 32410
          protocol: UDP
        - containerPort: 32412
          protocol: UDP
        - containerPort: 32413
          protocol: UDP
        - containerPort: 32414
          protocol: UDP
      volumeMounts:
        - mountPath: "/data"
          name: media
        - mountPath: "/config"
          name: config
    volumes:
      - name: media
        persistentVolumeClaim:
          claimName: nfs-mercury-media
      - name: config
        persistentVolumeClaim:
          claimName: nfs-mercury-config
    restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mercury-media
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - hard
    - vers=3
    - rsize=131072
    - wsize=131072
    - namlen=255
    - timeo=600
    - retrans=2
    - local_lock=none
  nfs:
    server: 192.168.1.149
    path: "/volume1/media"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mercury-config
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - hard
    - vers=3
    - rsize=131072
    - wsize=131072
    - namlen=255
    - timeo=600
    - retrans=2
    - local_lock=none
  nfs:
    server: 192.168.1.149
    path: "/volume1/docker-volumes/plex/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mercury-media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mercury-config
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: Service
metadata: 
  name: plex-service
spec:
  selector:
    app: plex
  type: NodePort
  ports:
  - name: plex
    port: 32400
    targetPort: 32400
    nodePort: 32400
    protocol: TCP

