apiVersion: v1
kind: Pod
metadata:
    name: sonarr
    labels:
      app: sonarr
spec:
    containers:
    - name: sonarr
      image: linuxserver/sonarr
      env:
        - name: TZ
          value: "America/New York"
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
      ports:
        - containerPort: 8989
          protocol: TCP
          hostPort: 8989
      volumeMounts:
        - mountPath: "/tv"
          name: media
        - mountPath: "/config"
          name: config
    nodeSelector:
      kubernetes.io/hostname: mars
    volumes:
      - name: media
        persistentVolumeClaim:
          claimName: nfs-mercury-media-tv
      - name: config
        persistentVolumeClaim:
          claimName: nfs-mercury-config-sonarr
    restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mercury-media-tv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - hard
    - vers=3
  nfs:
    server: 192.168.1.149
    path: "/volume1/media/tv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mercury-config-sonarr
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - hard
    - vers=3
  nfs:
    server: 192.168.1.111
    path: "/volume1/nas_share/docker/images/media/sonarr/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mercury-media-tv
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mercury-config-sonarr
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
---
